#Convert all police andmilitary actors to gov(country)
pth = 'C:/Users/salau/OneDrive - Michigan State University/Research/Fert_x_Conflict/'

load(paste0(pth, 'a1.rda'))

ids = c('actor1', "assoc_actor_1", 'actor2',"assoc_actor_2")


for (id in ids) {
  a1[, id][which(grepl("Military Forces of Nigeria", a1[, id]))] = "Gov(Nigeria)"
  a1[, id][which(grepl("Police Forces of Nigeria ", a1[, id]))] = "Gov(Nigeria)"
  a1[, id][which(grepl("Military Forces of Algeria", a1[, id]))] = "Gov(Nigeria)"
  a1[, id][which(grepl("Police Forces of Algeria", a1[, id]))] = "Gov(Algeria)"
  a1[,id][which(grepl("Military Forces of Benin", a1[, id]))] = "Gov(Benin)"
  a1[,id][which(grepl("Police Forces of Benin", a1[, id]))] ="Gov(Benin)"
  a1[,id][which(grepl("Military Forces of Botswana", a1[, id]))] ="Gov(Botswana)"
  a1[,id][which(grepl("Police Forces of Botswana", a1[, id]))] ="Gov(Botswana)"
  a1[,id][which(grepl("Military Forces of Burkina Faso", a1[, id]))] ="Gov(Burkina Faso)"
  a1[,id][which(grepl("Police Forces of Burkina Faso", a1[, id]))] ="Gov(Burkina Faso)"
  a1[,id][which(grepl("Military Forces of Mali", a1[, id]))] ="Gov(Mali)"
  a1[,id][which(grepl("Police Forces of Mali", a1[, id]))] ="Gov(Mali)"
  a1[,id][which(grepl("Military Forces of Burundi", a1[, id]))] ="Gov(Burundi)"
  a1[,id][which(grepl("Police Forces of Burundi", a1[, id]))] ="Gov(Burundi)"
  a1[,id][which(grepl("Military Forces of Cameroon", a1[, id]))] ="Gov(Cameroon)"
  a1[,id][which(grepl("Police Forces of Cameroon", a1[, id]))] ="Gov(Cameroon)"
  a1[,id][which(grepl("Military Forces of Canada", a1[, id]))] ="Gov(Canada)"
  a1[,id][which(grepl("Military Forces of Chad", a1[, id]))] ="Gov(Chad)"
  a1[,id][which(grepl("Police Forces of Chad", a1[, id]))] ="Gov(Chad)"
  a1[,id][which(grepl("Military Forces of Mauritania", a1[, id]))] ="Gov(Mauritania)"
  a1[,id][which(grepl("Police Forces of Mauritania", a1[, id]))] ="Gov(Mauritania)"
  a1[,id][which(grepl("Military Forces of Niger", a1[, id]))] ="Gov(Niger)"
  a1[,id][which(grepl("Police Forces of Niger", a1[, id]))] ="Gov(Niger)"
  a1[,id][which(grepl("Military Forces of Djibouti", a1[, id]))] ="Gov(Djibouti)"
  a1[,id][which(grepl("Police Forces of Djibouti", a1[, id]))] ="Gov(Djibouti)"
  a1[,id][which(grepl("Military Forces of Egypt", a1[, id]))] ="Gov(Egypt)"
  a1[,id][which(grepl("Police Forces of Egypt", a1[, id]))] ="Gov(Egypt)"
  a1[,id][which(grepl("Military Forces of United Arab Emirates", a1[, id]))] ="Gov(United Arab Emirates)"
  a1[,id][which(grepl("Military Forces of Equatorial Guinea", a1[, id]))] ="Gov(Equatorial Guinea)"
  a1[,id][which(grepl("Police Forces of Equatorial Guinea", a1[, id]))] ="Gov(Equatorial Guinea)"
  a1[,id][which(grepl("Military Forces of Eritrea", a1[, id]))] ="Gov(Eritrea)"
  a1[,id][which(grepl("Police Forces of Eritrea", a1[, id]))] ="Gov(Eritrea)"
  a1[,id][which(grepl("Military Forces of Estonia", a1[, id]))] ="Gov(Estonia)"
  a1[,id][which(grepl("Military Forces of eSwatini", a1[, id]))] ="Gov(eSwatini)"
  a1[,id][which(grepl("Police Forces of eSwatini", a1[, id]))] ="Gov(eSwatini)"
  a1[,id][which(grepl("Military Forces of Ethiopia", a1[, id]))] ="Gov(Ethiopia)"
  a1[,id][which(grepl("Police Forces of Ethiopia", a1[, id]))] ="Gov(Ethiopia)"
  a1[,id][which(grepl("Military Forces of Somalia", a1[, id]))] ="Gov(Somalia)"
  a1[,id][which(grepl("Police Forces of Somalia", a1[, id]))] ="Gov(Somalia)"
  a1[,id][which(grepl("Military Forces of France", a1[, id]))] ="Gov(France)"
  a1[,id][which(grepl("Military Forces of Gabon", a1[, id]))] ="Gov(Gabon)"
  a1[,id][which(grepl("Police Forces of Gabon", a1[, id]))] ="Gov(Gabon)"
  a1[,id][which(grepl("Military Forces of Gambia", a1[, id]))] ="Gov(Gambia)"
  a1[,id][which(grepl("Police Forces of Gambia", a1[, id]))] ="Gov(Gambia)"
  a1[,id][which(grepl("Military Forces of Ghana", a1[, id]))] ="Gov(Ghana)"
  a1[,id][which(grepl("Police Forces of Ghana", a1[, id]))] ="Gov(Ghana)"
  a1[,id][which(grepl("Military Forces of Guinea", a1[, id]))] ="Gov(Guinea)"
  a1[,id][which(grepl("Police Forces of Guinea", a1[, id]))] ="Gov(Guinea)"
  a1[,id][which(grepl("Military Forces of Guinea-Bissau", a1[, id]))] ="Gov(Guinea-Bissau)"
  a1[,id][which(grepl("Police Forces of Guinea-Bissau", a1[, id]))] ="Gov(Guinea-Bissau)"
  a1[,id][which(grepl("Military Forces of Israel", a1[, id]))] ="Gov(Israel)"
  a1[,id][which(grepl("Military Forces of Italy", a1[, id]))] ="Gov(Italy)"
  a1[,id][which(grepl("Military Forces of Jubaland", a1[, id]))] ="Gov(Somalia)"
  a1[,id][which(grepl("Military Forces of Kenya", a1[, id]))] ="Gov(Kenya)"
  a1[,id][which(grepl("Police Forces of Kenya", a1[, id]))] ="Gov(Kenya)"
  a1[,id][which(grepl("Military Forces of Lesotho", a1[, id]))] ="Gov(Lesotho)"
  a1[,id][which(grepl("Police Forces of Lesotho", a1[, id]))] ="Gov(Lesotho)"
  a1[,id][which(grepl("Military Forces of Liberia", a1[, id]))] ="Gov(Liberia)"
  a1[,id][which(grepl("Police Forces of Liberia", a1[, id]))] ="Gov(Liberia)"
  a1[,id][which(grepl("Military Forces of Libya", a1[, id]))] ="Gov(Libya)"
  a1[,id][which(grepl("Police Forces of Libya", a1[, id]))] ="Gov(Libya)"
  a1[,id][which(grepl("Military Forces of Madagascar", a1[, id]))] ="Gov(Madagascar)"
  a1[,id][which(grepl("Police Forces of Madagascar", a1[, id]))] ="Gov(Madagascar)"
  a1[,id][which(grepl("Military Forces of Malawi", a1[, id]))] ="Gov(Malawi)"
  a1[,id][which(grepl("Police Forces of Malawi", a1[, id]))] ="Gov(Malawi)"
  a1[,id][which(grepl("Military Forces of Mauritania", a1[, id]))] ="Gov(Mauritania)"
  a1[,id][which(grepl("Police Forces of Mauritania", a1[, id]))] ="Gov(Mauritania)"
  a1[,id][which(grepl("Military Forces of Morocco", a1[, id]))] ="Gov(Morocco)"
  a1[,id][which(grepl("Police Forces of Morocco", a1[, id]))] ="Gov(Morocco)"
  a1[,id][which(grepl("Military Forces of Mozambique", a1[, id]))] ="Gov(Mozambique)"
  a1[,id][which(grepl("Police Forces of Mozambique", a1[, id]))] ="Gov(Mozambique)"
  a1[,id][which(grepl("Military Forces of Namibia", a1[, id]))] ="Gov(Namibia)"
  a1[,id][which(grepl("Police Forces of Namibia", a1[, id]))] ="Gov(Namibia)"
  a1[,id][which(grepl("Military Forces of Pakistan", a1[, id]))] ="Gov(Pakistan)"
  a1[,id][which(grepl("Military Forces of Russia", a1[, id]))] ="Gov(Russia)"
  a1[,id][which(grepl("Military Forces of Senegal", a1[, id]))] ="Gov(Senegal)"
  a1[,id][which(grepl("Police Forces of Senegal", a1[, id]))] ="Gov(Senegal)"
  a1[,id][which(grepl("Military Forces of Sierra Leone", a1[, id]))] ="Gov(Sierra Leone)"
  a1[,id][which(grepl("Police Forces of Sierra Leone", a1[, id]))] ="Gov(Sierra Leone)"
  a1[,id][which(grepl("Military Forces of the United States", a1[, id]))] ="Gov(United States)"
  a1[,id][which(grepl("Military Forces of South Africa", a1[, id]))] ="Gov(South Africa)"
  a1[,id][which(grepl("Police Forces of South Africa", a1[, id]))] ="Gov(South Africa)"
  a1[,id][which(grepl("Military Forces of South Sudan", a1[, id]))] ="Gov(South Sudan)"
  a1[,id][which(grepl("Police Forces of South Sudan", a1[, id]))] ="Gov(South Sudan)"
  a1[,id][which(grepl("Military Forces of Southern Sudan", a1[, id]))] ="Gov(South Sudan)"
  a1[,id][which(grepl("Military Forces of Sudan", a1[, id]))] ="Gov(Sudan)"
  a1[,id][which(grepl("Police Forces of Sudan", a1[, id]))] ="Gov(Sudan)"
  a1[,id][which(grepl("Military Forces of Tanzania", a1[, id]))] ="Gov(Tanzania)"
  a1[,id][which(grepl("Police Forces of Tanzania", a1[, id]))] ="Gov(Tanzania)"
  a1[,id][which(grepl("Military Forces of the Central African Republic", a1[, id]))] ="Gov(CAR)"
  a1[,id][which(grepl("Police Forces of the Central African Republic", a1[, id]))] ="Gov(CAR)"
  a1[,id][which(grepl("Military Forces of the Democratic Republic of Congo ", a1[, id]))] ="Gov(DRC)"
  a1[,id][which(grepl("Police Forces of the Democratic Republic of Congo", a1[, id]))] ="Gov(DRC)"
  a1[,id][which(grepl("Military Forces of the Ivory Coast", a1[, id]))] ="Gov(Ivory Coast)"
  a1[,id][which(grepl("Police Forces of the Ivory Coast", a1[, id]))] ="Gov(Ivory Coast)"
  a1[,id][which(grepl("Military Forces of the Republic of Congo", a1[, id]))] ="Gov(Republic of Congo)"
  a1[,id][which(grepl("Police Forces of the Republic of Congo", a1[, id]))] ="Gov(Republic of Congo)"
  a1[,id][which(grepl("Military Forces of the United Kingdom", a1[, id]))] ="Gov(United Kingdom)"
  a1[,id][which(grepl("Military Forces of the United States", a1[, id]))] ="Gov(United States)"
  a1[,id][which(grepl("Military Forces of Togo", a1[, id]))] ="Gov(Togo)"
  a1[,id][which(grepl("Police Forces of Togo", a1[, id]))] ="Gov(Togo)"
  a1[,id][which(grepl("Military Forces of Turkey", a1[, id]))] ="Gov(Turkey)"
  a1[,id][which(grepl("Military Forces of Uganda", a1[, id]))] ="Gov(Uganda)"
  a1[,id][which(grepl("Police Forces of Uganda", a1[, id]))] ="Gov(Uganda)"
  a1[,id][which(grepl("Military Forces of Zambia", a1[, id]))] ="Gov(Zambia)"
  a1[,id][which(grepl("Police Forces of Zambia", a1[, id]))] ="Gov(Zambia)"
  a1[,id][which(grepl("Military Forces of Zimbabwe", a1[, id]))] ="Gov(Zimbabwe)"
  a1[,id][which(grepl("Police Forces of Zimbabwe", a1[, id]))] ="Gov(Zimbabwe)"
  a1[,id][which(grepl("Police Forces of Angola", a1[, id]))] ="Gov(Angola)"
  a1[,id][which(grepl("Police Forces of Somaliland", a1[, id]))] ="Gov(Somalia)"
  a1[,id][which(grepl("Military Forces of Somaliland", a1[, id]))] ="Gov(Somalia)"
}

a1 = a1[a1$actor1!=a1$actor2,]

#REMOVE ROWS THAT DONT HAVE AN ASSoC ACTOR TO FIGHT WITH
bat_cn_2 = a1[!c(a1$assoc_actor_1 == "", a1$assoc_actor_2 == "" ), ]

#export both
write.csv(bat_cn_2, paste0(pth, "BEV_cn_new.csv"))

